/// Regenerates `src/rti.rs` from the `.proto` files in `src/raw-proto/`.
/// Run via: `cargo run --example generate_protos && cargo fmt`
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").map_err(
        |_| "CARGO_MANIFEST_DIR not set — run this via `cargo run --example generate_protos`",
    )?);
    let src_dir = manifest_dir.join("src");
    let proto_dir = src_dir.join("raw-proto");

    let mut config = prost_build::Config::new();
    // Rithmic adds fields to existing messages in most template releases, so a
    // generated type without this makes every proto refresh a semver-major event here.
    config.type_attribute(".", "#[non_exhaustive]");
    // Rithmic deprecated entitlement_flag in template version 5.42 in favor of
    // the level_1_market_data / level_2_market_data fields.
    config.field_attribute(
        ".rti.ResponseListExchangePermissions.entitlement_flag",
        "#[deprecated = \"use level_1_market_data and level_2_market_data instead\"]",
    );
    config.out_dir(&src_dir);
    config.compile_protos(
        &[
            proto_dir.join("otps_proto_pool.proto"),
            // The 0.89.0.0 pool stopped importing these four, but the .proto
            // files still ship and templates 504/505 and 508/509 still answer,
            // so compile them alongside the pool.
            proto_dir.join("request_accept_agreement.proto"),
            proto_dir.join("response_accept_agreement.proto"),
            proto_dir.join("request_set_rithmic_mrkt_data_self_cert_status.proto"),
            proto_dir.join("response_set_rithmic_mrkt_data_self_cert_status.proto"),
        ],
        &[&proto_dir],
    )?;

    // MessageType is in a separate proto not referenced by the pool,
    // so we compile it separately and append it to the generated file.
    config.out_dir(std::env::temp_dir());
    config.compile_protos(&[proto_dir.join("message_type.proto")], &[&proto_dir])?;

    let message_type_code = std::fs::read_to_string(std::env::temp_dir().join("rti.rs"))?;

    // Read the pool-generated file, prepend `pub mod messages;` and append MessageType
    let pool_path = src_dir.join("rti.rs");
    let pool_code = std::fs::read_to_string(&pool_path)?;

    // Both halves are generated files, so both open with this line. Keep the one
    // `message_type_code` carries and drop the pool's, leaving a single header.
    const GENERATED_HEADER: &str = "// This file is @generated by prost-build.\n";
    let pool_body = pool_code
        .strip_prefix(GENERATED_HEADER)
        .ok_or("pool output does not start with the prost-build header")?;

    let combined = format!("pub mod messages;\n\n{message_type_code}{pool_body}");

    // Some Rithmic comments contain tabs, which prost copies into doc comments
    // and clippy rejects. Strip them here so a proto refresh cannot break the
    // build. Code is untouched — prost indents with spaces.
    let mut detabbed = String::with_capacity(combined.len());

    for line in combined.lines() {
        let trimmed = line.trim_start();

        if trimmed.starts_with("///") || trimmed.starts_with("//!") {
            detabbed.push_str(&line.replace('\t', " "));
        } else {
            detabbed.push_str(line);
        }

        detabbed.push('\n');
    }

    std::fs::write(&pool_path, detabbed)?;

    println!("Generated src/rti.rs — run `cargo fmt` to format it.");
    Ok(())
}
